# SPDX-FileCopyrightText: 2020 Benedict Harcourt
#
# SPDX-License-Identifier: BSD-2-Clause

name: "Add Remote Tag"
description: "Remotely add more tags to an existing docker image"

branding:
  icon: tag
  color: blue

inputs:
  registry:
    description: "Docker registry to talk to"
    required: true
  repository:
    description: "The name of the rpository to tag"
    required: true
  tag:
    description: "The tag to copy"
    required: true
  auth:
    descripton: "Authorization header to use for Docker API calls"
    required: false

outputs:
  exists:
    description: "1 if the image exists, 0 otherwise"

runs:
  using: "node12"
  main: "check-tag.js"

# vim: nospell ts=2 expandtab
